fi-ts/cloudctl

go.mod, go.sum
=> Update cobra to fix zsh completion

go.mod, go.sum
Fixes weird looking error messages.
=> Update metal-lib to v0.6.6.

cmd/cluster.go
add following flags to `cluster create|update`:
```
--draintimeout duration       period (e.g. "3h") after which a draining node will be forcefully deleted.
--healthtimeout duration      period (e.g. "24h") after which an unhealthy node is declared failed and will be replaced.
```
(custom mcm-settings require the machineControllerManagerOOT feature)
=> add machineControllerManager settings

cmd/cluster.go
default CRI is handled in cloud-api
=> do not set default cri on client-side

cmd/completion.go
=> zsh: fix wrong help text

cmd/completion.go, cmd/root.go, go.mod, go.sum
***Important***: change your .bashrc line to `source <(cloudctl completion bash)`
- support for bash, fish, zsh and Powershell completion
=> cobra now automagically creates a completion command

cmd/project.go, cmd/tenant.go
At least fix this to return a proper error message.
=> tenant apply errors out on new tenant

cmd/output/shootprinter.go
All clusters forcefully migrated to this new approach already, we can now delete this cluster issue.
=> Drop oot mcm cluster warning.

cmd/cluster.go
Related to https://github.com/metal-stack/metal-console/pull/18
=> firewall access is restricted to providertenants

.github/workflows/release.yml
currently no binary was uploaded for darwin/arm64
=> add release for darwin/arm64 as well

cmd/cluster.go
allow to reset machineControllerManager-settings back to provider-default
```
$ cloudctl cluster update 64ef4da2-e616-40ca-b162-5602d414cd2b --healthtimeout 24h --draintimeout 4h
$ k get shoot -n garden-pd76mr-9k77q inttest0 -o json | jq '.spec.provider.workers'
[
{
"cri": {
"name": "containerd"
},
"machine": {
"image": {
"name": "debian",
"version": "10.0"
},
"type": "c1-xlarge-x86"
},
"machineControllerManager": {
"machineDrainTimeout": "4h0m0s",
"machineHealthTimeout": "24h0m0s",
"maxEvictRetries": 720
},
"maxSurge": 1,
"maxUnavailable": 1,
"maximum": 1,
"minimum": 1,
"name": "group-0",
"systemComponents": {
"allow": true
}
}
]
$ cloudctl cluster update 64ef4da2-e616-40ca-b162-5602d414cd2b --healthtimeout 0
$ k get shoot -n garden-pd76mr-9k77q inttest0 -o json | jq …
```
=> allow to reset machineControllerManager-settings

README.md
Adds packaging status from repology.
=> README.md: add packaging status

cmd/billing.go, cmd/output/billingprinter.go
=> Improve billing subcommand descriptions and add missing env vars.

cmd/output/volume.go
=> Normal non-admin users always see 0b usage

cmd/project.go, cmd/tenant.go, go.mod, go.sum
=> Add filters for `tenant ls` and `project ls`

cmd/billing.go, cmd/output/billingprinter.go, cmd/output/order.go, cmd/output/printer.go, go.mod, go.sum
Can be used to find all projects within a given time period, e.g. to narrow down queries that would become very big otherwise.
=> Add `billing projects` command to discover accounting projects.

cmd/output/printer.go, cmd/output/projectprinter.go, cmd/output/tenantprinter.go
=> Show quotas only on `project describe`.

cmd/cluster.go, go.mod, go.sum
closes https://github.com/fi-ts/cloudctl/issues/212
requires https://github.com/fi-ts/cloud-go/pull/84
=> add --workertaints to cluster update

cmd/output/machine.go
This way it fits into one line of the terminal. 🙈
=> More condensed `cluster machine ls`.

cmd/postgres.go
=> Honour the `--yes-i-really-mean-it` flag when deleting databases

Makefile, cmd/output/shootprinter.go
Closes https://github.com/fi-ts/cloudctl/issues/252.
=> Link linux binary statically.

cmd/postgres.go
Fixing #192 for the proper resource
=> Honour the --yes-i-really-mean-it flag when deleting database backups

cmd/login.go, go.mod, go.sum
Before this, always latest was downloaded and after login the call to the /version endpoint was not authenticated.
Fix both
=> Download the desired version and relogin

cmd/cluster.go, cmd/output/shootprinter.go
First try on hopefully little improved help texts for cluster isolation.
=> Try improving help texts a little.

cmd/completion/completion.go, cmd/root.go
=> Fix completion.

cmd/cluster.go, go.mod
=> Fix `cluster machine ls` output.

cmd/dashboard.go
Closes https://github.com/fi-ts/cloudctl/issues/312
=> print release version on dashboard

cmd/cluster.go
related to https://github.com/fi-ts/cloud-api/pull/33
=> do not default workersizes on client side
