cmd/ip.go
adds `--name --description` options to `cloudctl ip static`
```
Usage:
cloudctl ip static <ip> [flags]
Flags:
--description string   set description of the ip address [optional]
-h, --help                 help for static
--name string          set name of the ip address [optional]
```
```
$ cloudctl ip static 212.34.83.5 --name mwentest --description "test ip static"
IP              TYPE    NAME            NETWORK         PROJECT                                 TAGS
212.34.83.5     static  mwentest        internet        cd4eac58-46a5-4a31-b59f-2ec207baa817    service:ded51942-192b-4daf-b5b1-622b072cc58b/default/echoserver
$ cloudctl ip ls -o wide| grep 212.34.83.5
212.34.83.5     static          mwentest                                                        test ip static  internet …
```
=> add options to set name/description for "cloudctl ip static"

cmd/cluster.go
otherwise it can happen, that shoots have their seed in a wrong partition
(see https://gardener.cloud/documentation/concepts/core-components/scheduler/#special-handling-based-on-shoot-cluster-purpose)
=> remove testing purpose

cmd/cluster.go, cmd/output/printer.go
If somebody uses `-o json` or `-o yaml` it is expected that the output of cloudctl returns JSON / YAML. At the moment, though, we return multiple objects for `cluster machine ls` and `cluster logs` containing headings in between the output, which makes the output hard for users to process.
This PR prints more original payload without the additional formatting that is applied for the table printer output.
=> Fix invalid JSON output for cluster machine ls and cluster logs.

cmd/output/shootprinter.go
For clusters with CRI=containerd, the RUNTIME contains an additional wrong `docker`
```
UID                                     NAME            VERSION PARTITION       DOMAIN                                  OPERATION       PROGRESS                API     CONTROL NODES   SYSTEM  SIZE    AGE     PURPOSE PRIVILEGED      RUNTIME         FIREWALL                        EGRESS IPS 
9529c143-b78d-4ec4-a041-3b86626126cc    mycluster1      1.18.12 stg-kkw701      mycluster1.p5mlcn.cluster.fits.cloud    Succeeded       100% [Reconcile]        True    True    True    True    1≤1≤1   5h 33m  prod    false           docker          firewall-ubuntu-2.0.20201126              
containerd                       
```
with this fix:
```
UID                                     NAME            VERSION …
```
=> fix cri output for containerd clusters

cmd/cluster.go, cmd/helper/kubeconfig.go
I started to use this part of cloudctl in order to assemble the Kubeconfig for integration tests. Can we make this public?
=> Factor out kubeconfig template merge in order to make it re-usable.

.gitignore, cmd/output/printer.go, cmd/root.go, cmd/version.go, cmd/whoami.go, pkg/api/version.go
cc @majst01 
Output looks similar to `metalctl version` command:
If server is available:
```
client: 1.1, go1.16.5
server:
builddate: "2021-03-29T11:30:07Z"
gitsha1: e843d254
name: metal-api
revision: tags/v0.14.1-0-ge843d25
version: v0.14.1
```
If not available:
```
client: 1.1, go1.16.5
Error: failed to get server info: Get "http://localhost:8080/cloud/v1/version": dial tcp 127.0.0.1:8080: connect: connection refused
```
=> added version cmd

cmd/postgres.go, go.mod, go.sum
```
cloudctl postgres edit ade2ed7b-3bdd-4863-b234-edbdbf43a89c
panic: interface conversion: interface {} is *models.V1PostgresCreateRequest, not *models.V1PostgresUpdateRequest
goroutine 1 [running]:
github.com/fi-ts/cloudctl/cmd.readPostgresUpdateRequests.func1(0x24994e0, 0xc000724000)
/work/cmd/postgres.go:526 +0x166
github.com/fi-ts/cloudctl/cmd/helper.ReadFrom(0xc0007ea140, 0x47, 0x24994e0, 0xc000724000, 0xc00015bb58, 0xb, 0xc)
/work/cmd/helper/helper.go:125 +0x1d9
github.com/fi-ts/cloudctl/cmd.readPostgresUpdateRequests(0xc0007ea140, 0x47, 0xc0000a2168, 0x0, 0x0, 0x0, 0x0)
/work/cmd/postgres.go:525 +0xa5
github.com/fi-ts/cloudctl/cmd.postgresEdit.func2(0xc0007ea140, 0x47, 0x0, 0x1)
/work/cmd/postgres.go:504 +0x3c
github.com/fi-ts/cloudctl/cmd/helper.Edit(0x76b4937, 0x24, 0x2677a70, …
```
=> Fix interface conversion during pg edit

cmd/cluster.go, cmd/completion.go, cmd/postgres.go
It was not possible to get a completion to certain commands which require the already selected  cluster as input, e.g.
`cloudctl cluster machine console 8fef639c-bbe4-4c6f-9656-617dc4a4efd8 --machineid <tab><tab>` did not return the machines attached to this cluster.
Now:
```
cloudctl cluster machine console 8fef639c-bbe4-4c6f-9656-617dc4a4efd8 --machineid 00000000-0000-0000-0000-ac1f6b7b
00000000-0000-0000-0000-ac1f6b7b77c8  (shoot--test--fra-equ01-firewall-c9d01)              00000000-0000-0000-0000-ac1f6b7bed30  (shoot--test--fra-equ01-default-worker-5f9b5-ltk9g)
```
Also add descriptions to the completion suggestions that makes decision more simple:
```
cloudctl cluster logs 
256ca952-0c0f-4d62-aabf-da4e6f3e9183  (s3-test-01)  5c985fdf-6c26-4cf3-96a0-8de97d9ffeee  (behinddmz) …
```
=> enable dynamic completion based on previous selected cluster

README.md
`cloudctl` is now packaged as [nix](https://nixos.org) package. Added description to `README.md`.
see https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/admin/fits-cloudctl/default.nix
=> README: add installation with the nix package manager

cmd/postgres.go
For whatever reaseon, we decided not to use nillable values for some params in the `V1PostgresUpdateRequest`. Those need to be send to the API in order to prevent them being overwritten with the default value.
=> Fix Postgres Promote/Demote Calls

cmd/cluster.go
```
$ cloudctl  cluster update d277a293-0bbc-42d7-94d4-0886cd43c72a --maxsize 1 --minsize 1
WARNING. New maxsize is lower than currently active machines. A random worker node which is still in use will be removed.
Are you sure? (y/n) y
```
=> warn if reducing maxsize will remove a node

cmd/output/volume.go
Reverts fi-ts/cloudctl#167, fix is required in cloud-api
=> Revert "Normal non-admin users always see 0b usage"

cmd/cluster.go
I think this behavior is a bit "friendlier" during node rolls.
```BREAKING_CHANGE
The max unavailable setting for nodes of a cluster worker group is now defaulted to `0` instead of `1`.
```
=> Default max unavailable worker group nodes to 0 instead of 1.

.gitignore, cmd/cluster.go, cmd/root.go
prevents segfault with invalid workergroup name:
```
$ cloudctl  cluster update 4e21f74e-8134-417f-b474-785332e58b3c --workergroup blafasel --remove-workergroup 
WARNING. Removing a worker group cannot be undone and causes the loss of local data on the deleted nodes.
Are you sure? (y/n) y
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x117369a]
goroutine 1 [running]:
github.com/fi-ts/cloudctl/cmd.(*config).updateCluster(0xc000516240, {0xc00083a1c0, 0x1, 0x4})
/work/cmd/cluster.go:954 +0x1dba
```
=> validate workergroup name before removal

cmd/postgres.go
As discussed on friday: Implementation of the missing `cloudctl postgres backup-config describe <ID>` subcommand.
On the server-side, everything we need is already present.
=> Add missing postgres backup-config describe cmd

cmd/cluster.go
will be set to true in cloud-api anyway
=> remove --reversed-vpn for cluster create

Makefile
Unfortunately, GNU date produces a date with the `--rfc-3339=seconds` that Golang cannot parse with it's RFC3339 format definition.
Instead we need to use the `--iso-8601=seconds` flag, which is at least parsable with Go.
Here I demonstrate the behavior: https://go.dev/play/p/FSXBzJcqpUA
There is also a good blog article talking about this issue and where it comes from: https://utcc.utoronto.ca/~cks/space/blog/unix/GNUDateAndRFC3339
Other repositories where we need to apply this change to:
The bug was introduced in this commit: https://github.com/fi-ts/cloudctl/pull/248/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52
Closes #258.
=> For build date use Go-compatible RFC3339 date format, fixes `update check`

Makefile
Last release results into:
```
❯ ~/Downloads/cloudctl update check 
checksum:7ad8446e9de3edeebdc8eb2d5d9a3351
Error: parsing time "2023-09-13T09:02:01+00:00 ": extra text: " "
```
Because the comment in the Makefile added a whitespace character to the end of the date. 🙄
=> Second fix on date format: Remove whitespace that came from comment.

cmd/postgres.go
Currently, when creating a new postgres instance, the `version` flag is optional and defaults to `12`.
Since everyone uses a different "default" version anyway, this PR removes the default value and makes the `version` flag a required flag.
=> Postgres: Require version flag on creation, remove default value

cmd/output/printer.go
Nicer output when using conditionals in template output.
Before:
```
$ cloudctl cluster ls -o template --template '{{ if eq .Networking.Type "cilium" }}{{ .Name }}{{end}}'
cilium
```
With this PR:
```
$ cloudctl ls -o template --template '{{ if eq .Networking.Type "cilium" }}{{ .Name }}{{end}}'
cilium
```
=> skip printing empty rows in tablePrinter

cmd/s3.go
=> Better error message if s3 deletion takes longer than 30s.

cmd/printers.go, cmd/tableprinters/printer.go
This will allow us to slowly migrate to the genericcli table printer. It will fall back to the old output package printer implementation in case the printer does not match any known types.
=> Add transition code to allow migration to genericcli table printer

cmd/postgres.go
The current version does not report invalid timestamps. Postgreslet does report it, but you have to dig through its logs on the k8s cluster, which is cumbersome. The better variant is to report the error directly to the user.
=> throw an error if supplied pg restore timestamp is wrongly formatted

README.md, cmd/s3.go
Print `mc alias set` instead of `mc config host add`
Tested `mc alias set` with:
Closes: https://github.com/fi-ts/cloudctl/issues/343
=> fix --for-client=minio output for newer mc versions
